[package]
name = "dawn"
version = "2.1.0-access-domain"
description = "DAWN Access-Domain Program (lean build)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dawn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
devnet = []
default = []
idl-build = ["anchor-lang/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }

[build-dependencies]
toml = "0.7"
