[package]
name = "dawn"
version = "0.1.0"
description = "DAWN Protocol Program"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "lib"]
name = "dawn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
devnet = []
default = []

[dependencies]
anchor-lang = "=0.29.0"
anchor-spl = "=0.29.0"
raydium-cp-swap = { git = "https://github.com/raydium-io/raydium-cp-swap", features = [
    "no-entrypoint",
    "cpi",
] }
solana-program = ">=1.16, <1.18"
spl-memo = "4.0.0"

[build-dependencies]
toml = "0.7"
