[package]
name = "dawn"
version = "1.0.2"
description = "DAWN Protocol Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dawn"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
devnet = ["raydium-cp-swap/devnet"]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
mpl-token-metadata = "5.1.1"
raydium-cp-swap = { git = "https://github.com/raydium-io/raydium-cp-swap", default-features = false, features = [
    "no-entrypoint",
    "cpi",
] }
spl-memo = "6.0.0"

[build-dependencies]
toml = "0.7"
