[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
dawn = "4yBWXvJ2otyMvkBewgKhnkJ7WP1c7HHDSicdQwH4dXqC"

[programs.devnet]
dawn = "dawnt36j2ej84PXrEjrxDjmQb5nAAqCVwTP8f1Y1aYu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
