[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dawn = "BNf8E3y61JVMzm65Va5rzacyec8axAx86YvvjZwBvx6S"

[programs.devnet]
dawn = "11111111111111111111111111111111"  # Placeholder program ID

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
