[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
dawn = "F4Yq1jQgccrzbEn9iHrA9JjQ1xyRFViDX8Xhb5FzJmaE"

[programs.devnet]
dawn = "Fgnro1Xh59RyYiArHHEmNZ1TryTXsLtdu9fKDeQ86thz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn test"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
