[package]
name = "plan"
version = "0.1.0"
description = "DAWN Plan Subscription Program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "plan"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
anchor-spl = "0.30.1"
spl-memo = "5.0.0"
raydium-clmm = { path = "../../raydium", features = ["no-entrypoint", "cpi"] }
# raydium-amm-v3 = { git = "https://github.com/raydium-io/raydium-clmm.git", branch = "master", features = [
#     "no-entrypoint",
# ] }
