name: Check PR

on:
  push:
    branches: [dev, master, feat/DAWN-21/ci-tests]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # CACHE
      - name: Cache Solana and Anchor CLI
        uses: actions/cache@v4
        id: cli-cache
        with:
          path: |
            ~/.local/share/solana/install
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/solana
          key: ${{ runner.os }}-solana-anchor-cli
          restore-keys: |
            Linux-solana-anchor-cli

      # RUST
      - name: Install Rust toolchain
        run: rustup default 1.79.0

      # SOLANA
      - name: Install Solana CLI
        if: steps.cli-cache.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
      - name: Set Solana CLI path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # ANCHOR
      - name: Install Anchor CLI
        if: steps.cli-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli

      # GENERATE KEY
      - name: Generate new keygen
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new --no-bip39-passphrase

      # CONFIG
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get

      # DEPENDENCIES
      - name: Install yarn dependencies
        run: yarn install

      # BUILD
      - name: Build
        run: anchor build

      # TESTS
      - name: Run tests
        run: anchor test
