name: Check PR

on:
  push:
    branches: [dev, master]
  pull_request:
    branches: [dev, master]

jobs:
  check:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Rust toolchain
        uses: actions/cache@v4
        id: rust-cache
        with:
          key: ${{ runner.os }}-rust-1.87.0
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git

      # RUST
      - name: Install Rust toolchain
        if: steps.rust-cache.outputs.cache-hit != 'true'
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.87.0
          components: clippy, rustfmt

      - name: Install build essentials
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install yarn
        run: corepack enable yarn

      - name: Check fmt
        run: cargo fmt --check

      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # CACHE SOLANA
      - name: Cache Solana CLI
        uses: actions/cache@v4
        id: solana-cache
        with:
          path: |
            ~/.local/share/solana/install
            ~/.cache/solana
          key: ${{ runner.os }}-solana-2.1.0

      # SOLANA
      - name: Install Solana CLI
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.0/install)"
      - name: Set Solana CLI path
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # CACHE ANCHOR
      - name: Cache Anchor CLI
        uses: actions/cache@v4
        id: anchor-cache
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-anchor-0.31.1

      # ANCHOR
      - name: Install Anchor CLI
        if: steps.anchor-cache.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli

      # GENERATE KEY
      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase

      # CACHE DEPENDENCIES
      - name: Cache NodeJS dependencies
        uses: actions/cache@v4
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      # DEPENDENCIES
      - name: Install yarn dependencies
        run: yarn install

      # CACHE BUILD
      - name: Cache Rust & Anchor dependencies
        uses: actions/cache@v4
        id: build-cache
        with:
          path: target
          key: ${{ runner.os }}-anchor-build-${{ hashFiles('**/Cargo.lock') }}

      # BUILD
      - name: Build
        run: anchor build

      # TESTS
      - name: Run tests
        run: anchor test
