name: Check PR

on:
  push:
    branches: [dev, master, feat/DAWN-21/ci-tests]
  pull_request:
    branches: [dev]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Solana and Anchor CLI
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/share/solana/install
            ~/.cargo/bin
          key: ${{ runner.os }}-solana-anchor-cli
      - name: Install Rust toolchain
        run: rustup default 1.79.0
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.0/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
      - name: Install Anchor CLI
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 anchor-cli
      - name: Generate new keygen
        run: |
          mkdir -p ~/.config/solana
          solana-keygen new
      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899
      - name: Check solana config
        run: solana config get
      - name: Install yarn dependencies
        run: yarn install
      - name: Build
        run: anchor build
      - name: Run tests
        run: anchor test
